// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myprojectbahaa.Data;

#nullable disable

namespace myprojectbahaa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("myprojectbahaa.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Player1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 1,
                            Player2Id = 2,
                            Score1 = 3,
                            Score2 = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 1,
                            Player2Id = 3,
                            Score1 = 2,
                            Score2 = 0
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 2,
                            Player2Id = 4,
                            Score1 = 4,
                            Score2 = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 3,
                            Player2Id = 5,
                            Score1 = 1,
                            Score2 = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 1,
                            Player2Id = 4,
                            Score1 = 5,
                            Score2 = 0
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 2,
                            Player2Id = 5,
                            Score1 = 3,
                            Score2 = 2
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 3,
                            Player2Id = 4,
                            Score1 = 2,
                            Score2 = 1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Player1Id = 1,
                            Player2Id = 5,
                            Score1 = 4,
                            Score2 = 1
                        });
                });

            modelBuilder.Entity("myprojectbahaa.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsScored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Draws = 2,
                            GoalsConceded = 18,
                            GoalsScored = 38,
                            Losses = 3,
                            Name = "Ahmed Al-Rashid",
                            Username = "AhmedR",
                            Wins = 12
                        },
                        new
                        {
                            Id = 2,
                            Draws = 2,
                            GoalsConceded = 24,
                            GoalsScored = 29,
                            Losses = 6,
                            Name = "Omar Khalid",
                            Username = "OmarK",
                            Wins = 9
                        },
                        new
                        {
                            Id = 3,
                            Draws = 3,
                            GoalsConceded = 27,
                            GoalsScored = 25,
                            Losses = 7,
                            Name = "Yusuf Demir",
                            Username = "YusufD",
                            Wins = 7
                        },
                        new
                        {
                            Id = 4,
                            Draws = 2,
                            GoalsConceded = 33,
                            GoalsScored = 19,
                            Losses = 10,
                            Name = "Tariq Hassan",
                            Username = "TariqH",
                            Wins = 5
                        },
                        new
                        {
                            Id = 5,
                            Draws = 2,
                            GoalsConceded = 36,
                            GoalsScored = 15,
                            Losses = 11,
                            Name = "Bilal Sahin",
                            Username = "BilalS",
                            Wins = 4
                        });
                });

            modelBuilder.Entity("myprojectbahaa.Models.Match", b =>
                {
                    b.HasOne("myprojectbahaa.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myprojectbahaa.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });
#pragma warning restore 612, 618
        }
    }
}
